#
# Copyright 2022 Intel Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Default values for image location internal installation and agent. Use localhost:5001 (local provider registry) until images will be published.
images:
- name: gardener-extension-cri-resmgr-installation
  sourceRepository: https://github.com/intel/gardener-extension-cri-resmgr
  repository: localhost:5001/gardener-extension-cri-resmgr-installation
  tag: latest
- name: gardener-extension-cri-resmgr-agent
  sourceRepository: https://github.com/intel/cri-resource-manager
  repository: docker.io/intel/cri-resmgr-agent
  # Please keep this in sync with CRI_RM_VERSION from Makefile!
  tag: v0.7.2
